train_processing:
  scale_factor: 51
  train_df: 'Inputs/train.csv'
  train_series_meta: 'Inputs/train_series_meta.csv'
  train_merged: 'Outputs/Preprocessing/merged_dataframe.csv'
  segmentation_dir: 'Inputs/segmentations'
  mask_dir: 'Outputs/Preprocessing/masks'
  annotation_dir: 'Outputs/Preprocessing/annotations'
  train_images_dir : 'Inputs/train_images/'
  train_images_png_dir : 'Outputs/Preprocessing/train_images_png/'
  final_train_images_png_dir : 'Outputs/Preprocessing/final_train_images_png/'
  final_mask_dir : 'Outputs/Preprocessing/final_masks'
  final_annotation_dir : 'Outputs/Preprocessing/final_annotations'
  matched_train_images_dir : 'Outputs/Preprocessing/matched_train_images' 
  dataset_dir : 'Outputs/Preprocessing/datasets/data'
  split_ratio: 0.7
  matched_output_path: 'Outputs/Preprocessing/matched_series_ids.json'
  unmatched_output_path:  'Outputs/Preprocessing/unmatched_series_ids.json'
 

test_processing:
  test_images_dir : 'Inputs/test_images/'
  final_test_images_png_dir: 'Outputs/Preprocessing/test_images_png/' 

log:
  log_file: 'log/log.txt'