train: E:\MS_AI_ML\Dissertation\Abdominal\Outputs\Validation\Segmentor_Model\modelling\spleen\datasets\data\train\images
val: E:\MS_AI_ML\Dissertation\Abdominal\Outputs\Validation\Segmentor_Model\modelling\spleen\datasets\data\valid\images
nc: 3  # number of classes
names: ['spleen_healthy', 'spleen_low', 'spleen_high']







